let tank = require('../../../utils/tank');

tank('inmyroom / admin / tank', {
  auth: true,

  links: [
    '/admin/orders',
    '/admin/orders/deleted',
    '/admin/orders/logistic',
    '/admin/orders/analytics',
    '/admin/product_categories/new',
    '/admin/posts',
    '/admin/sale_posts',
    '/admin/quizzes',
    '/admin/meter/posts',
    '/admin/meter/teasers',
    '/admin/chronology',
    '/admin/crm/employees',
    '/admin/crm/suppliers',
    '/admin/inquiries',
    '/admin/inquiries/declined',
    '/admin/crm/logistic/calendars',
    '/admin/crm/logistic/delivery_calendars',
    '/admin/crm/logistic/payment_calendars',
    '/admin/crm/quality_controls',
    '/admin/regional_shipping_methods',
    '/admin/companies',
    '/admin/yml_imports',
    '/admin/moderator/products',
    '/admin/moderator/products/inbox',
    '/admin/brands',
    '/admin/moderator/photos',
    '/admin/moderator/comments',
    '/admin/promo_projects',
    '/admin/banner_places',
    '/admin/banners',
    '/admin/metatags',
    '/admin/metatag_variables',
    '/admin/declensions',
    '/admin/static_pages',
    '/admin/meter',
    '/admin/meter/companies',
    '/admin/search/stats',
    '/admin/search',
    '/admin/dashboard',
    '/admin/users',
    '/admin/badges',
    '/admin/user_professions',
    '/admin/company_types',
    '/admin/tags',
    '/admin/tag_categories',
    '/admin/tags/duplicates',
    '/admin/commerce_categories',
    '/admin/commerce_category_groups',
    '/admin/product_categories',
    '/admin/product_categories/stats',
    '/admin/crm/stocks/standart_stock',
    '/admin/crm/stocks/return_stock',
    '/admin/uploads/1',
    '/admin/forums',
    '/admin/forums/pereplanirovki',
    '/admin/own_companies'
  ]
})
